import './globals.css'
import { Inter } from 'next/font/google'
import classNames from "classnames";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Vercel\'s Lore',
  description: 'Generated by their future intern',
  openGraph: {
    images: '/og-me.png'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={classNames(inter.className, "bg-default dark:bg-defaultDark")}>{children}</body>
    </html>
  )
}
